import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { buildMarkdownDocument } from './documentGenerator';

export const buildReportFilename = (title = 'report') =>
  `${String(title || 'report')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'report'}.pdf`;

export const buildReportHtml = (report = {}) => {
  const title = String(report.title || report.heading || 'MineShield Report').trim();
  const sections = Array.isArray(report.sections) ? report.sections : [];
  const markdown = buildMarkdownDocument({ title, sections });

  const sectionMarkup = sections
    .map(
      (section) => `
        <section style="margin-bottom: 18px;">
          <h2 style="margin: 0 0 8px; font-size: 18px;">${String(section.heading || '').replace(/</g, '&lt;')}</h2>
          <p style="margin: 0; font-size: 13px; line-height: 1.55;">${String(section.body || '').replace(/</g, '&lt;')}</p>
        </section>
      `
    )
    .join('');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${title.replace(/</g, '&lt;')}</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 24px; color: #1E334F; }
      h1 { font-size: 26px; margin: 0 0 20px; }
      .meta { color: #5A6A79; font-size: 12px; margin-bottom: 20px; }
      pre { white-space: pre-wrap; background: #F4F7FB; border: 1px solid #D7E2EF; padding: 12px; border-radius: 10px; }
    </style>
  </head>
  <body>
    <h1>${title.replace(/</g, '&lt;')}</h1>
    <div class="meta">Generated by MineShield</div>
    ${sectionMarkup}
    <h2 style="font-size: 18px; margin-top: 26px;">Raw Notes</h2>
    <pre>${markdown.replace(/</g, '&lt;')}</pre>
  </body>
</html>`;
};

export const exportReportToPdf = async (report = {}) => {
  const html = buildReportHtml(report);
  const result = await Print.printToFileAsync({ html });
  return result?.uri || null;
};

export const shareReport = async (report = {}) => {
  const uri = await exportReportToPdf(report);

  if (!uri) {
    return null;
  }

  if (!(await Sharing.isAvailableAsync())) {
    return uri;
  }

  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    UTI: 'com.adobe.pdf',
  });

  return uri;
};

export default {
  buildReportFilename,
  buildReportHtml,
  exportReportToPdf,
  shareReport,
};
